name: testing.ato

on:
  workflow_dispatch:
    inputs:
      ALLURE_JOB_RUN_ID:
        description: ALLURE_JOB_RUN_ID - service parameter (leave blank)
        required: false
      ALLURE_USERNAME:
        description: ALLURE_USERNAME - service parameter (leave blank)
        required: false
      BROWSER:
        required: true
        default: Chrome
      ENDPOINT:
        required: true
        default: testing.testops.cloud
      OS:
        required: true
        default: macOS
      VERSION:
        required: true
        default: 5.8.0
      ALLURECTL_VERSION:
        required: true
        default: 2.15.1
        # Information about allurectl releases is available on https://github.com/allure-framework/allurectl/releases

env:
  ALLURE_ENDPOINT: https://testing.testops.cloud/
  ALLURE_PROJECT_ID: 9301
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURECTL_VERSION: ${{ github.event.inputs.ALLURECTL_VERSION }}
  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
  ALLURE_RESULTS: "build/allure-results"
  ALLURE_TESTPLAN_PATH: "./testplan.json"

jobs:
  java_autotests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
                 
      - name: Install allurectl
        uses: allure-framework/setup-allurectl@v1
        with:
          ALLURE_ENDPOINT: ${{ github.event.inputs.ALLURE_ENDPOINT}}
          ALLURE_PROJECT_ID: ${{ github.event.inputs.ALLURE_PROJECT_ID}}
          ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
          ALLURECTL_VERSION: ${{ github.event.inputs.ALLURECTL_VERSION }}
          ALLURE_LAUNCH_NAME: "GitHub - Test Run #${{ github.run_number }}"
          
      - name: Run tests
        run: |
          chmod +x ./gradlew 
          allurectl watch -- ./gradlew clean test
        env:
          ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
          ALLURE_RESULTS: "build/allure-results"
          ALLURE_TESTPLAN_PATH: "./testplan.json"
          ALLURE_LAUNCH_NAME: "GitHub - Test Run #${{ github.run_number }}"
          BRANCH: ${{ github.ref_name }}
          BROWSER: ${{ github.event.inputs.BROWSER}}
          ENDPOINT: ${{ github.event.inputs.ENDPOINT}}
          OS: ${{ github.event.inputs.OS}}
          VERSION: ${{ github.event.inputs.VERSION}}
